Improve Javadocs
vaadin/flow-components pull request #2937
Opened 2022-03-25 13:05 UTC by tarekoraby

The new descriptions of the components are mostly taken from their descriptions in the [docs](https://vaadin.com/docs/latest/ds/components). 

For example, instead of the Button docs saying
```
/**
 * Server-side component for the <code>vaadin-button</code> element.
 */
```

It will be changed to say
```
/**
 * The Button component allows users to perform actions. It comes in several
 * style variants, and supports icons in addition to text labels.
 */
```

2022-03-25 14:29 UTC, tarekoraby commented
This PR doesn't include the full list of components yet. But I'd like to see if it's ready to be merged so that I can estimate the amount of effort needed to complete the full list of components.

2022-03-29 16:45 UTC, sissbruecker requested changes
Thanks for the effort, this is definitely an improvement.

However I think we should be more careful about consistency, for example there are still several components with a leading introduction of:
```
Server-side component for the {@code vaadin-checkbox} element.
```
I think we can resolve these in some way. I would suggest to take a look at these together, feel free to ping me for a organizing a pairing session.

2022-03-29 16:45 UTC, sissbruecker commented on vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java
> + *
```suggestion
 * content at a time.
 * <p>
```
For separating JavaDoc into paragraphs we usually use HTML paragraphs. Also no need for blank lines in between.

Please update the other occurrences accordingly.

2022-03-30 07:44 UTC, tarekoraby commented
For the record, we agreed to take the task of improving the docs of the rest of the components in a separate PR.

2022-03-30 14:51 UTC, sissbruecker approved these changes

2022-03-30 14:51 UTC, merged