Adding backported functionalities to DatePicker (version is 14.9, backported from the latest version of it 24-Snapshot)
vaadin/flow-components pull request #4354
Opened 2022-12-14 10:23 UTC by czp13

## Description

The customer agreed to sponsor the reference date feature and backport it from our latest flow-components version:
Related support ticket: 
- https://support.vaadin.com/projects/VS/queues/custom/3/VS-4437
Related github ticket:
- https://github.com/vaadin-component-factory/enhanced-date-picker/issues/16

The issues in the customer's words:

> If I set the parser pattern "ddMMyy" and the formatting pattern "dd.MM.yyyy" to the enhanced-date-picker, the following input "101070" is parsed to "10.10.2070". I think it makes more sense to parse this input to "10.10.1970" in context of date of birth, for example.
> Is there a way to manually set the breakpoint where the parser switches from 2000 to 1900?
> 

Fixes # (issue)
- Added prepare-frontend maven goal to datepicker so now the mvn build will be successful and the application can be run on the local machine, otherwise, the frontend was not ready and some assets were not bundled to the Jetty web server,
- added NPMPackage "date-fns" , this is needed as we build open this package the feature,
- added reference date feature to DatePicker Java class,
- added reference date feature to datePicker connector JS class, also parsing changed to use date-fns parsing methods,

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-12-14 14:32 UTC, web-padawan requested changes
Thanks for the PR. This change was a new feature and IMO it is not feasible to land in a patch release.
Also, implementing it would require a corresponding change in the web component first.

We need to agree if this is something that we want to be part of Vaadin 14.10

2022-12-14 14:35 UTC, TatuLund commented
> We need to agree if this is something that we want to be part of Vaadin 14.10

@web-padawan Yes, you are correct. The branch is wrong, I just noticed it myself too. The simple reason is that 14.10 branch has not been created yet.

2022-12-27 09:40 UTC, ZheSun88 commented
I removed the `target/14.9`  label. 
after this PR #4441  you can push to 14.10 branch.

2022-12-27 10:03 UTC, web-padawan commented
This PR still needs a change in the web component to be implemented first (needs a minor bump).

2023-01-04 13:18 UTC, czp13 commented
Executed another build as the last build was lost from TeamCity, and picked up this one today again.

2023-01-18 15:49 UTC, czp13 commented
Rebase and some other related changes happened, let's see the result of this build.

2023-01-18 19:44 UTC, czp13 commented
Locally the tests are good, so quiet weird behavior, I think something about the run config, or locale is not matching with my dev environment vs the build server:
![image](https://user-images.githubusercontent.com/61667986/213279237-7734822c-d58a-41ff-bcc2-fa03711e5bce.png)

2023-01-20 09:20 UTC, ZheSun88 commented
Hi @czp13 , the failed test in the validation is running under bower mode, did you run that in your local? 

i just tried on my side, seems getting the same failure.

2023-01-20 12:32 UTC, czp13 commented
> Hi @czp13 , the failed test in the validation is running under bower mode, did you run that in your local?
> ...
Thank you vm @ZheSun88! I hit the wall so hard with this one, but this can push me forward I feel/hope.
I used this command: 
` mvn -pl vaadin-date-picker-flow-integration-tests clean jetty:run`
And was scratching my hand about the difference between team city build agent and my env, but I will try with bower too, just remember I had some issues with it... I will get back to this.

2023-01-20 19:48 UTC, czp13 commented
I can confirm with your bower environment variable I can reproduce the bugs in my local environment, finally, I can move forward with this one. Thank you 🙇 🙏 (Just to not be easy, we need to use JDK 18 and also pom.xml needed to be changed, to remove the deprecated JVM param, but apart from that it works)

2023-01-24 11:35 UTC, czp13 commented
I figured out the bower part with the help of @ZheSun88.
Fingers crossed this will be good now, then I will clean up a bit, and THEN hopefully good to go (merge).

2023-01-27 08:26 UTC, sissbruecker requested changes

2023-01-27 14:52 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow-demo/pom.xml
> +         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
Done, thanks.

2023-01-27 14:53 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerViewDemoPage.java
> +        datePicker.setI18n(i18n);
Thanks for this as well.

Added all tests I could, which was not trivial not just back-porting as some pages/IT classes were looking differently, and other things were missing too, or needed to add, changes, but I believe now we covered the cases which we had in the original PR.

2023-01-27 14:54 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> +// @HtmlImport("frontend://bower_components/vaadin-date-picker/src/vaadin-accordion.html")
Good point, I wanted to backport this bit as well, as it was part of the backported PR, but it was not working for bower, and then I spent quite many time to figure out what is going on, I saw this workaround with `vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns` and the only reason I could fix the PR that I understood what we are doing here (needed to change JS classes to use this directory date-fns version not from NPM, etc...

2023-01-27 14:55 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
> + * components are themeable:
I try to follow the boy-scout rule, meaning try to fix everything I see on the way (like README.md which was fully outdated), but I reverted back this bit for now.

2023-01-27 14:55 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
> +        return window.Vaadin.Flow.tryCatchWrapper(callback, 'Vaadin Date Picker');
Same here, it was in the PR looking like that, but reverted back! Thanks for noting.

2023-01-27 14:56 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
> +                 */
Nice catch, thank you, fixed it! (side effect of tons of refactor, trials :) )

2023-01-27 14:56 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
> +                    const isValidPattern = pattern.includes('d') && pattern.includes('M') && pattern.includes('y');
Nice one, I fixed this everywhere I see in that class! 🙇

2023-01-27 14:56 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
> +                function _parseDate(str) {
Changed this as you wished as well!

2023-01-27 14:57 UTC, czp13 commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
> +                function _parseDate(str) {
And thanks for all the comments, review 👏 🙇

2023-01-30 10:49 UTC, sissbruecker approved these changes

2023-01-30 10:51 UTC, merged