chore: Update vaadin commercial license (V22.1) [skip ci]
vaadin/flow-components pull request #4832
Opened 2023-03-20 12:35 UTC by ZheSun88

2023-03-21 06:32 UTC, ZheSun88 commented
this will need flow 9.1-snapshot to run.

2023-04-06 09:45 UTC, alvarezguille commented on vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
Some files like `Board.java` have double license header mentioning both CVDL and new commercial license and service terms

2023-04-06 12:02 UTC, ZheSun88 commented on vaadin-board-flow-parent/vaadin-board-flow/src/main/java/com/vaadin/flow/component/board/Board.java
rechecked all the files and updated.

2023-04-06 12:31 UTC, alvarezguille requested changes
* `Apache License` is still mentioned in some `README.md` files and 
* Some components have the new license headers but still have apache headers like `LoginForm` or `AppLayout`
* `CVDLv4` is mentioned in asciidoc, the whole ` vaadin-charts-flow-parent/documentation` directory can be removed as done in #4259

2023-04-06 12:59 UTC, alvarezguille approved these changes

2023-04-06 12:59 UTC, merged