fix: Email pattern accepts double dot between domain and tld (vaadin/flow#17333)
vaadin/flow-components pull request #5320
Opened 2023-08-03 05:16 UTC by gronono

## Description

As indicated in issue https://github.com/vaadin/flow/issues/17333, this PR changes the validation pattern of an email address by invalidating the dot-dot in the domain name.

In https://github.com/vaadin/flow/pull/17353, I made EmailValidator.PATTERN public to use it in EmailField class. So the pattern is not longer duplicates between EmailValidator and EmailField

Fixes vaadin/flow#17333

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
- [ ] I have not completed some of the steps above and my pull request can be closed immediately.

2023-08-03 05:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-components?pullRequest=5320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-components?pullRequest=5320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-components?pullRequest=5320) it.</sub>

2023-08-03 12:07 UTC, vursen requested changes
Blocked by:

- https://github.com/vaadin/flow/pull/17353

2023-08-04 09:05 UTC, gronono commented
> Thank you for the contribution. The PR is blocked until the corresponding one in the `flow` repository is merged.
> 
> * [fix: reject emails with double dot between domain and tld flow#17353](https://github.com/vaadin/flow/pull/17353)

The PR has been merged by @mcollovati

2023-08-04 10:03 UTC, vursen commented
Closing in favor of https://github.com/vaadin/flow-components/pull/5327 to run the build.

2023-08-04 10:03 UTC, closed without merging