fix: Throw when calling click on disabled button
vaadin/flow-components pull request #5392
Opened 2023-08-28 14:34 UTC by TatuLund

2023-08-31 13:01 UTC, vursen requested changes
Could you please reference a ticket? It's required for review.

2023-09-01 14:50 UTC, TatuLund commented
@vursen I created the ticket and linked it.

2023-09-18 12:55 UTC, vursen reviewed
I'd argue against throwing exceptions and suggest just ignoring such clicks. This would align with the native browser behavior which ignores programmatic clicks on disabled buttons without throwing any exceptions:

```html
<button disabled>Click!</button>
<script>
const button = document.querySelector('button');
button.addEventListener('click', () => {
  console.log('click');
});
button.click();
</script>
```

2023-10-17 07:34 UTC, yuriy-fix commented
@TatuLund, is it Ok if we adjust the PR to avoid throwing an exception?

2023-10-17 08:45 UTC, TatuLund commented
@yuriy-fix basically yes, but what is your idea for change?

2023-10-24 07:07 UTC, yuriy-fix commented
Following https://github.com/vaadin/flow-components/pull/5392#pullrequestreview-1630981248 comment, ignore  programmatic clicks on disabled buttons without throwing exceptions.

2023-11-01 10:14 UTC, vursen commented on vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java
> +    public void disableOnClick_clickRevertsDisabled_componentIsEnabled() {
**note:** The previous version of the test attempted to click the disabled button and that expectedly stopped working after the PR change.

2023-11-01 10:57 UTC, vursen commented on vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/Button.java
> +                    false, false, false));
**note:** It seems that you can still get click triggered on a disabled button by manually firing this click event.

2023-11-02 07:44 UTC, vursen approved these changes

2023-11-02 07:46 UTC, merged