fire the OpenedChangeEvent for the opened-changed dom event
vaadin/flow-components pull request #5413
Opened 2023-09-01 11:05 UTC by sujoykd

## Description

Fixes #5386

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
- [ ] I have not completed some of the steps above and my pull request can be closed immediately.

2023-09-01 13:17 UTC, web-padawan requested changes
Let's also check other components that might be affected, see https://github.com/vaadin/flow-components/issues/5386#issuecomment-1702694823

2023-09-01 13:30 UTC, sujoykd commented
> Let's also check other components that might be affected, see [#5386 (comment)](https://github.com/vaadin/flow-components/issues/5386#issuecomment-1702694823)

I am checking the other components that might be affected.
However, the fix for #4909 was released on 24.0.5, but this current issue is also present in 24.0.4

2023-09-04 13:59 UTC, web-padawan commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> +    @Synchronize(property = "opened", value = { "opened-changed" })
```suggestion
    @Synchronize(property = "opened", value = "opened-changed")
```

2023-09-04 14:01 UTC, web-padawan approved these changes

2023-09-04 19:21 UTC, ugur-vaadin approved these changes
I checked the other components as well. The `@Synchronize` annotation appears to be missing only from this one. It seems that it was mistakenly removed while removing the deprecated generated classes. I wonder if we should introduce (out of the scope of this PR&issue) similar tests for all the component listeners that depend on DOM events.

2023-09-05 06:49 UTC, merged