feat: split char into ligature and char
vaadin/flow-components pull request #5436
Opened 2023-09-06 11:08 UTC by tomivirkki

## Description

Related to https://github.com/vaadin/web-components/pull/6452

As a follow-up of the `FontIcon` DX test results, we decided to split the `FontIcon::setChar`, which currently accepts either a code point or a ligature, into separate `FontIcon::setChar` and `FontIcon::setLigature` methods.

Since "char" can no longer be a ligature name, the updated `FontIcon::setChar` method now also supports unprefixed code points (like "ea0e").

Before:
```java
var lumoIcon = new FontIcon();
lumoIcon.setFontFamily("lumo-icons");
lumoIcon.setChar("\uea0e");

var materialIcon = new FontIcon();
materialIcon.setFontFamily("Material Icons");
materialIcon.setChar("face");
```

After:
```java
var lumoIcon = new FontIcon();
lumoIcon.setFontFamily("lumo-icons");
lumoIcon.setChar("ea0e");

var materialIcon = new FontIcon();
materialIcon.setFontFamily("Material Icons");
materialIcon.setLigature("face");
```

## Type of change

Feature

2023-09-11 11:26 UTC, DiegoCardoso requested changes

2023-09-11 11:26 UTC, DiegoCardoso commented on vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/FontIcon.java
> +     * Gets the hexadecimal code point that specifies a glyph from an icon font.
"Gets the ligature" instead?

2023-09-11 12:45 UTC, tomivirkki commented on vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/FontIcon.java
> +     * Gets the hexadecimal code point that specifies a glyph from an icon font.
Done.

2023-09-12 09:04 UTC, DiegoCardoso approved these changes

2023-09-12 10:34 UTC, tomivirkki commented
Let's wait for the next web component alphas including the related API changed before merging.

2023-09-12 10:39 UTC, merged