fix: make form layout responsive steps getter work properly
vaadin/flow-components pull request #6252
Opened 2024-04-26 14:44 UTC by akhodyko

## Description
Form layout responsive steps getter does not work at all.
Included test describes the case.

## Type of change

- [x] Bugfix
- [ ] Feature

2024-04-26 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-components?pullRequest=6252) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-components?pullRequest=6252) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-components?pullRequest=6252) it.</sub>

2024-04-26 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-components?pullRequest=6252) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-components?pullRequest=6252) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-components?pullRequest=6252) it.</sub>

2024-04-29 13:07 UTC, vursen requested changes
Thank you for your contribution. Please note that ResponsiveStep can be also initialized without minWidth, and this currently results in an exception. This case needs to be addressed as well.

P.S I'm a bit surprised that ResponsiveStep doesn't provide any getters, which means getResponsiveSteps has very limited practical value, as it only provides information on the number of added steps.

2024-04-30 07:55 UTC, yuriy-fix commented
Dear @akhodyko, the API has been confirmed to not be working properly and it should be fixed. Could you please share your use case for the API usage, so enhancements can be considered along the way and corresponding issues can be created?

2024-05-02 09:10 UTC, akhodyko commented on vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
> +        public ResponsiveStep() {
it's possible to make this constructor private and replace a 
```JsonSerializer.toObjects(ResponsiveStep.class, stepsJsonArray);```
with
```
List<ResponsiveStep> steps = new ArrayList<>();
for (int i = 0; i < stepsJsonArray.length(); i++) {
    steps.add(new ResponsiveStep().readJson(stepsJsonArray.get(i)));
}
return steps;
```

2024-05-02 09:10 UTC, akhodyko commented on vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
> +        formLayout.setResponsiveSteps(new ResponsiveStep(null, 1));
done

2024-05-07 10:52 UTC, vursen commented
We had an internal discussion and decided to reuse the existing public constructor instead of introducing a new private one. We can always add the default constructor later if there is a request for it. I've updated the PR accordingly.

2024-05-07 11:01 UTC, vursen approved these changes

2024-05-07 11:24 UTC, merged