docs(DatePicker, TimePicker): explain constraint validation
vaadin/flow-components pull request #6537
Opened 2024-08-12 09:34 UTC by vursen

## Description

- [x] Give a general description of how the constraint validation works, including such aspects as validation triggers, constraints, error messages, Binder, manual validation.
- [x] For setErrorMessage, mention i18n as the means for setting distinct error messages.
- [x] For setErrorMessage, explain that the error message will be only displayed when the field is 
- [x] For constraint methods like setMin, setMax, mention that they are inclusive.

Part of https://github.com/vaadin/flow-components/issues/6545

## Type of change

- [x] Docs

2024-08-12 12:54 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * The following constraints are available:
```suggestion
 * The following constraints can be set:
```

2024-08-12 12:55 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * Error messages for constraint violations, including unparsable input, can be
```suggestion
 * Error messages for constraint violations and unparsable input, can be
```

2024-08-12 12:55 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * Error messages for constraint violations and unparsable input, can be
```suggestion
 * Error messages for constraint violations and unparsable input can be
```

2024-08-12 12:58 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * Error messages for constraint violations and unparsable input can be
```suggestion
 * Error messages for unparsable input and constraint violations can be
```

2024-08-12 13:00 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * Error messages for unparsable input and constraint violations can be provided
```suggestion
 * Error messages for unparsable input and constraint violations can be configured
```

2024-08-13 05:07 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * <h3>Validation</h3>
```suggestion
 * <h2>Validation</h2>
```

2024-08-13 05:15 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * configured using the {@link DatePickerI18n} object.
```suggestion
 * configured using the respective methods in the {@link DatePickerI18n} object.
```

2024-08-13 05:57 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * <p>
**open question:** Does Binder need to be mentioned?

2024-08-14 12:19 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * satisfies the defined constraints. If validation fails, the component is
```suggestion
 * satisfies the specified constraints. If validation fails, the component is
```

2024-08-14 12:27 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * The following constraints can be set:
```suggestion
 * The following constraints are supported:
```

2024-08-14 14:12 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * configured using the respective methods in the {@link DatePickerI18n} object.
```suggestion
 * configured using the respective properties in the {@link DatePickerI18n} object.
```

2024-08-14 14:13 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * DatePicker comes with a built-in validation mechanism based on constraints.
```suggestion
 * Date Picker comes with a built-in validation mechanism based on constraints.
```

2024-08-14 14:20 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * configured using the respective properties in the {@link DatePickerI18n} object.
```suggestion
 * configured with the respective properties in the {@link DatePickerI18n} object. If you want to
 * provide a single error message for all constraints, you can also use the
 * {@link #setErrorMessage(String)} method. Note that error messages set with
 * {@link #setErrorMessage(String)} will take priority over i18n error messages.
```

2024-08-14 14:21 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * provide a single error message for all constraints, you can also use the
```suggestion
 * provide a single error message for all constraints, including unparsable input, you can also use the
```

2024-08-15 05:18 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> + * using error messages from the component's i18n object.
```suggestion
 * For more advanced validation that requires custom rules, you can use
 * {@link Binder}. By default, before running custom validators, Binder will
 * also check if the date is parsable and satisfies the component constraints
 * using error messages from the component's i18n object.
```

2024-08-21 08:21 UTC, vursen commented on vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> +     * Distinct error messages depending on constraints and for unparsable input
```suggestion
     * Distinct error messages for unparsable input and different constraints
```

2024-08-23 12:02 UTC, rolfsmeds requested changes
See my comments in the corresponding TextField PR :)

2024-08-26 08:33 UTC, vursen commented
> See my comments in the corresponding TextField PR :)

Updated DatePicker based on the TextField PR.

2024-09-17 08:55 UTC, web-padawan approved these changes

2024-09-17 09:17 UTC, web-padawan approved these changes

2024-09-17 09:27 UTC, web-padawan approved these changes

2024-09-17 11:59 UTC, rolfsmeds approved these changes

2024-09-17 12:23 UTC, merged