Cherry-pick: dialog shortcut fixes to 14.5
vaadin/flow-components pull request #765
Opened 2021-03-25 11:59 UTC by pleku

2021-03-29 09:03 UTC, sosa-vaadin requested changes
Compilation and tests are broken. An enum is missing but should've not been implemented anyway since this PR is about a different feature anyway. Please remove unrelated code to fix build and tests.

2021-04-01 08:36 UTC, pleku commented on vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
>          implements HasComponents, HasSize {
Fixed

2021-04-01 08:37 UTC, pleku commented on vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
> +    public void addThemeVariants(DialogVariant... variants) {
Fixed

2021-04-01 09:03 UTC, sosa-vaadin approved these changes

2021-04-07 07:06 UTC, merged